- id: trivy-fs
  name: trivy filesystem scan
  description: Run Trivy to scan the repository filesystem for vulnerabilities
  entry: trivy fs
  language: python
  pass_filenames: false

- id: trivy-config
  name: trivy config scan
  description: Run Trivy to scan IaC configuration files for misconfigurations
  entry: trivy config
  language: python
  pass_filenames: false

